### PR TITLE
guard include directory statements with condition on whether or not d…

### PR DESCRIPTION
**Pull request by rpcme**
…ependencies are being built

*Issue #, if available:*

Not available.

*Description of changes:*

Make guards for dependent cmake scripts for subcomponents so when you run a build with all dependencies already installed you can just use those - like a Yocto based build.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jmklix** [comment]
can this be applied more generally for other statements?

**Review by justinboswell — COMMENTED** [review]
Can you just add a comment explaining why this is here for the next unsuspecting person to end up in here? Otherwise, LGTM.

**Comment by rpcme** [comment]
Hello @justinboswell I couldn't see a common mechanism because there is a mix a things that required guards across all those cmakefiles.  OTOH I am not in CMake every day so it could be lost on me.

**Comment by rpcme** [comment]
> can this be applied more generally for other statements?

I couldn't see a good pattern other than creating new flags which only makes it more complex. I think reusing the flag and having a per-cmakefile change creates the least friction for the person running the cmakefile

**Review by sdavtaker — APPROVED** [review]
I think commit messages can be improved, but the rebase in the middle is making it harder to address it now.

**Review by sdavtaker — APPROVED** [review]

**Comment by rpcme** [comment]
@justinboswell can this be pulled in yet?

**Review by justinboswell — APPROVED** [review]

**Pull request merged**
